### PR TITLE
Start a run for windows python 3.6 and 3.7

### PR DESCRIPTION
**Pull request by hmaarrfk**
Continues the work of #38 where we still need to fix the builds for python 3.7 on windows

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Lets monitor on azure as well
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=3811

it might just be appveyor.

**Comment by hmaarrfk** [comment]
@jakirkham Azure seems to be passing. What do you think about me adding the flags to make azure upload this package?

**Comment by hmaarrfk** [comment]
@jakirkham I was working on some pytorch stuff, and my rerendering might have been out of date, though the only thing I hacked in it was the fix for the azure pipelines.

Will my mods to conda-forge.yml make azure upload the packages?

**Comment by hmaarrfk** [comment]
Even azure is givimg:
```
2019-01-04T08:07:22.2187193Z Command "D:\bld\scikit-image_1546589029628\_h_env\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-build-qobvptd4\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\VSSADM~1\AppData\Local\Temp\pip-record-6wdxj55u\install-record.txt --single-version-externally-managed --compile" failed with error code 3221225477 in C:\Users\VSSADM~1\AppData\Local\Temp\pip-req-build-qobvptd4\
```

**Comment by hmaarrfk** [comment]
It seems somebody else is having issues with long paths in windows 

https://github.com/cython/cython/issues/2515

**Comment by hmaarrfk** [comment]
https://github.com/rust-lang/rust/issues/33434

Pystan thinks it is a maximum path length issue too!!!!
https://github.com/stan-dev/pystan/issues/317

**Comment by hmaarrfk** [comment]
https://github.com/openai/mujoco-py/issues/68

**Comment by hmaarrfk** [comment]
@matthew-brett I'm dying here. For some reason python 3.7 on windows keeps failing. 

My current hunch is either:

1. The pathname is too long.
2. The cythonized code in the pypi src dist is too old to run well on python 3.7 windows.

Do you have any hunch as to which one might actually be the case?

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Can't you just enable long-path support in Windows?
https://docs.python.org/3/using/windows.html?highlight=longpathsenabled#removing-the-max-path-limitation

In powershell you can to that with:
```powershell
Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1;
```

**Comment by hmaarrfk** [comment]
@mingwandroid knows that it is in the prefix mangling at the end.


but he thinks it is related to this:
https://stackoverflow.com/questions/51816639/setup-py-egg-info-error-code-3221225477


He thinks that the default prefix is about 41 characters long. so making it 50 would make it more likely.

We can try 37

**Comment by hmaarrfk** [comment]
@dhirschfeld hopefully that works

**Comment by hmaarrfk** [comment]
sorry @dhirschfeld seems like it is still happening.

**Comment by hmaarrfk** [comment]
The last thing we can try is VS2017.....

**Comment by hmaarrfk** [comment]
or to make that path shorter as ray suggested.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
4/4 builds passed. I even added numpy 1.11 to the test section to confirm that it works.

**Comment by hmaarrfk** [comment]
Hi @conda-forge/core,

Please move my package
scikit-image win64 builds 1000 and 1001 only
 from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because on windows, pip was pulling in dependencies from pyproject.toml and building against modern versions of numpy as described in https://github.com/conda/conda-build/issues/3318

It didn't seem to occur in other operating systems.

**Comment by jni** [comment]
@hmaarrfk 😵🥇 🎉 🎉 🎉

**Comment by ocefpaf** [comment]
> Hi @conda-forge/core,
> 
> Please move my package
> scikit-image win64 builds 1000 and 1001 only
> from `main` to `broken` on the conda-forge channel on anaconda.org
> because on windows, pip was pulling in dependencies from pyproject.toml and building against modern versions of numpy as described in [conda/conda-build#3318](https://github.com/conda/conda-build/issues/3318)

Done. Can you check if I got the right ones?

https://anaconda.org/conda-forge/scikit-image/files?version=0.14.1&channel=broken

**Comment by hmaarrfk** [comment]
Thanks @ocefpaf you did. New packages should be getting built now!

**Comment by hmaarrfk** [comment]
@ocefpaf looking back, it seems that I also need 1002 on windows removed. I had back ported a fix a for numpy 1.16 on that one.

I noticed that all platforms uploaded 1004, so you can remove anything older than that really if that makes your life easier.

**Comment by hmaarrfk** [comment]
I think it should be OK. From what I remember the _0 builds were OK on windows since they were using a non-problematic version of conda-build.

Thanks Felipe!!!!

**Pull request merged**
