### PR TITLE
Numpy pinning

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Comment by jni** [comment]
@hmaarrfk care to explain these PRs? =) I don't know what you're trying to achieve...

**Comment by hmaarrfk** [comment]
Just kinda keeping things updates before I forget about other conversations.

I think older numpy is being left to rot pretty soon, and thus we would have to update the two recipes pretty soon

**Comment by jni** [comment]
> I think older numpy is being left to rot pretty soon

References to justify this statement would be useful I think. =) Not that I question it, just that it might help others to understand why the changes in this PR take the specific form they take, and why things might be failing. Are there other similar PRs being made against e.g. sklearn?

Also there's two PRs — was that just to try different things in parallel?

**Comment by hmaarrfk** [comment]
Here is the ref.

Sorry for not including it.

The other is to the 0.14 branch.

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/228

**Comment by jakirkham** [comment]
Is this still needed in light of PR ( https://github.com/conda-forge/scikit-image-feedstock/pull/49 )?

**Comment by hmaarrfk** [comment]
yeah, this one goes for 0.15

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
