### PR TITLE
MNT: remove double dependency on dask core

### PR DESCRIPTION
**Pull request by hmaarrfk**
Remove double dependency on dask
    
    - Remove build dep on numpy doc
    - Add cytoolz as a dependency for speed
    - Update build command

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@ocefpaf I have no idea why appveyor is failing. something about pip?

https://ci.appveyor.com/project/conda-forge/scikit-image-feedstock/build/1.0.115/job/u9rh9ilhm03bhlj2#L1126

**Comment by ocefpaf** [comment]
@hmaarrfk I think it may be an issue with the latest `Python` in Windows b/c I saw similar errors on other compiled extensions that were working not long ago, like `basemap` here:

https://github.com/conda-forge/basemap-feedstock/pull/34

@scopatz and @mariusvniekerk are actively working on the Python packages and can probably comment more on this.

**Comment by hmaarrfk** [comment]
@ocefpaf got it. the celiagg feedstock was giving similar errors. I'll just wait.

**Comment by hmaarrfk** [comment]
Removed in favour of #33

**Pull request closed without merging**
