### PR TITLE
V0.17.1

### PR DESCRIPTION
**Pull request by emmanuelle**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
soo strange that osx is failing alone. DId you ahve this issue for wheels as well?

**Comment by hmaarrfk** [comment]
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=158918&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=4455

**Comment by jni** [comment]
All's well that ends well, I say! :grinning:

**Comment by emmanuelle** [comment]
@hmaarrfk did you "just" restart the build and then finally it worked? I had pushed an empty commit to restart the build but the same test failed. With the wheels everything worked the first time. Thanks anyway!

**Comment by hmaarrfk** [comment]
Yeah. I just wanted to fix the linter

**Pull request merged**
