### PR TITLE
Patch 0.17.2

### PR DESCRIPTION
**Pull request by hmaarrfk**
@scikit-image/core do we have issues patching things like this?

I guess maybe i can just devote some time this weekend to 0.17.3, but conda-forge is so easy...
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jni @emmanuelle @sciunto

**Comment by sciunto** [comment]
I've never maintained this package. Perhaps you wanted to ping @soupault ?

**Comment by jni** [comment]
@hmaarrfk well, everything is broken at the moment. =P Can you give the background of all the other changes? (eg build NumPy version).

I'd prefer a release, though, as it needs to happen anyway after we fix a bunch of those segfaults. Happy to pair with you on the release if you are ok working in the evenings your time...

**Comment by jni** [comment]
@sciunto never too late to get started! =P

**Comment by hmaarrfk** [comment]
The question was a little philosophical more than practical.

The failure seelms related to a radon transform patch.

The build version is numpy 1.16

**Comment by hmaarrfk** [comment]
Hey @jni, if you aren't feeling this particular PR, maybe just close it for me.

Patching things on the distribution side is always controversial.

I'm happy to apply this patch on my private channel.

**Comment by hmaarrfk** [comment]
@jni we really need to make the scikit-image release process easier.

Even with everybody on board for a release, it is so hard to pull the trigger.

**Comment by jni** [comment]
Ha, we haven't even *hit* the release process yet, we've just agreed on the PRs to push through! 😂 Maybe I should pull the trigger on 0.17.3... Thoughts?

Anyway, I agree a lot. In case you didn't see it we applied for CZI EOSS for next year to do just this. 🤞

**Comment by hmaarrfk** [comment]
I'm down for "tag any commit".

I mostly don't want to break anybody's code for what can seem like a rushed released.

I'll probably just post this on my own channel and see what happens to me.

I'm mostly scared that this warning will turn into a behavior change for me.

Lets put our efforts on releasing something.

I would rather organize the PRs to create release notes for 0.18 instead of 0.17.3

I wonder if my old script still works.

**Pull request closed without merging**
