### PR TITLE
Build a package for 0.13dev

### PR DESCRIPTION
**Pull request by ivoflipse**
We wanted to try the new marching cubes, so I'm trying to make a dev package, hoping conda's version management doesn't go auto-updating everyone's skimage

### CODE REVIEW

**Comment by msarahan** [comment]
@jjhelmus has a good example of a pre-release package setup in https://github.com/conda-forge/python-feedstock/pull/45 - it takes care of putting the package under a different label.

**Comment by ivoflipse** [comment]
Thanks for the suggestion @msarahan I'll try and take that into account. Wouldn't want people's skimage's to start updating because of this

**Comment by jakirkham** [comment]
Though have we really settled on a way to dev releases. ( https://github.com/conda-forge/conda-forge.github.io/issues/147 )

**Comment by msarahan** [comment]
In the absence of the better conda support that you suggest in that issue, please do not hold up this PR.  @jjhelmus's scheme is not ideal, but it is proven and accepted, and in the absence of something better, we should use it.

**Comment by jakirkham** [comment]
> it is proven and accepted

Ok, could you please point out where that is the case? I have been operating under the pretext that we still have not settled on something and that we are not ready to propagate such changes through conda-forge. Particularly this [comment]( https://github.com/conda-forge/matplotlib-feedstock/pull/24#issuecomment-221496870 ). To be specific this text from @pelson.

> I'm not keen for this pattern to be rolled out wider at this stage - I'd like for the release candidate discussion to take place on the conda-forge hangout so that we can put together a coherent strategy for doing this kind of thing

Though if something has changed that I have missed, please let me know. I would love if there is a standard practice for such a thing, but it is not clear to me there is.

**Comment by msarahan** [comment]
@pelson, please confirm, but I think the approach in the python feedstock that I pointed out was discussed and agreed on at SciPy.  It is disappointing that there is no documentation other than the example, for sure.  We should bring this up at the meeting on Friday, just to make sure everyone is on the same page.  I'm OK with holding off until then.

**Comment by jakirkham** [comment]
Sorry, if you guys picked a way to do this at SciPy. I'm :+1: on going forward with it. Not interested in bikeshedding. Just was unaware that something was picked to be a standard.

:+1: on having docs. Is there a hack pad or something for this procedure? Would be great to have something to point people to.

**Comment by jakirkham** [comment]
There was an odd failure one of the Travis CI builds so restarted it. AppVeyor fails on Python 3.5.

**Comment by ivoflipse** [comment]
I don't understand where the AppVeyor error is coming from. 

```
compiling C sources
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
creating build\temp.win-amd64-3.5\Release\skimage
creating build\temp.win-amd64-3.5\Release\skimage\_shared
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\conda\envs\_build\lib\site-packages\numpy\core\include -IC:\conda\envs\_build\include -IC:\conda\envs\_build\include -IC:\conda\envs\_build\Library\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcskimage\_shared\geometry.c /Fobuild\temp.win-amd64-3.5\Release\skimage\_shared\geometry.obj
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\conda\envs\_build\libs /LIBPATH:C:\conda\envs\_build\PCbuild\amd64 /LIBPATH:C:\conda\envs\_build\Library\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64 /EXPORT:PyInit_geometry build\temp.win-amd64-3.5\Release\skimage\_shared\geometry.obj /OUT:build\lib.win-amd64-3.5\skimage\_shared\geometry.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\skimage\_shared\geometry.cp35-win_amd64.lib
Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe
LINK : fatal error LNK1181: cannot open input file 'Files.obj'
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\conda\envs\_build\libs /LIBPATH:C:\conda\envs\_build\PCbuild\amd64 /LIBPATH:C:\conda\envs\_build\Library\lib /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.14393.0\um\x64 /EXPORT:PyInit_geometry build\temp.win-amd64-3.5\Release\skimage\_shared\geometry.obj /OUT:build\lib.win-amd64-3.5\skimage\_shared\geometry.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\skimage\_shared\geometry.cp35-win_amd64.lib" failed with exit status 1181
Command failed: C:\windows\system32\cmd.exe /c bld.bat
Command exited with code 1
```

**Comment by msarahan** [comment]
I think it's related to https://github.com/pypa/setuptools/issues/728 - pinning setuptools to a 23.x release might work.

**Comment by Korijn** [comment]
LGTM!

@ivoflipse

**Comment by ivoflipse** [comment]
If @jakirkham and @msarahan have no further objections, this is GTG for me.

**Comment by msarahan** [comment]
@ivoflipse, we (conda-forge) need to nail down pre-release standards before we can merge this.  I was wrong about the Python pre-release being an agreed-on way to go.

At our meeting on Friday, no one wanted to take this up.  I have little time to spend here, but would be willing to write up what happens in the Python PR as a first draft for discussion.  If you have time to comment and help move that forward, it would help us get this PR merged.  I'll post back later today with a link to the draft.

**Comment by jakirkham** [comment]
Closing as 0.13 has been released. ( https://github.com/conda-forge/scikit-image-feedstock/pull/8 )

**Comment by jni** [comment]
@jakirkham @msarahan what's the status of pre-release builds on conda-forge? That would still be a useful thing to note here.

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/3 ). We have tried it in a few cases, but the process isn't really nailed down yet. It would be good to finalize the process so we can provide some guidelines.

**Pull request closed without merging**
